### ISSUE TITLE
Problem with Singularity

### ISSUE THREAD

**Issue by shahriar49** [davidfrantz/force#204] opened 2022-07-29 20:54 UTC
I  am a user of a Linux cluster where we have singularity module available but not docker.  I think I should be able to simply run force by issuing:
`singularity exec docker://davidfrantz/force:latest force `

But after downloading the container, I get below error at the prompt:
`FATAL:   "force": executable file not found in $PATH`

I am not an experienced singularity/docker user. Could you please help me what can I do to resolve this issue?

**Comment by davidfrantz** [comment] 2022-08-01 12:04
Hi @shahriar49,

it works fairly well on my end. Is the error message showing up direcly after the displayed command (singularity exec)? Or is it happening with a new command not shown in your post?

Best,
David

**Comment by shahriar49** [comment] 2022-08-02 16:20
Hi @davidfrantz ,
When I issue the singularity exec command, it starts downloading and making the image and it is ok, but then it looks that it tries to execute the force command from the downloaded image and it can not find it. So it looks like the $PATH setting is problematic in my environment or downloaded image file. Should I do something else?

Best Regards
Shahriar

**Comment by shahriar49** [comment] 2022-08-02 23:02
Update:
I asked our Linux cluster support guys and here is their answer:

*********************************************************************
"The issue is that the developer is installing the software in the $HOME directory of the container (/home/docker). Singularity, which enables the use of Docker containers in HPC environments (Docker can't be used on HPC because it requires root privileges), automatically bind mounts the host system's /home directory to the container's /home directory, which makes the container's /home directory invisible at run time (i.e., there is no ability to "see" /home/docker, which I believe is where the developer may have installed "force").
 
An easy solution would be to modify the Dockerfile that was used to build the container, which is here:
 
https://github.com/davidfrantz/force/blob/master/Dockerfile
 
...to do so, you could download the Dockerfile to your laptop, modify it by replacing each instance of "$HOME" with "/opt", then rebuild the container. ("docker build -t yourdockerrepo:containername ."). Then, push the container up to your docker repo, and access it from Summit. The executable, I think, will be in /opt/force"
*********************************************************************
 
I neither have Linux set up in my own computer /laptop nor I think it will be easy to set up all the software requirements and dependencies to be able to build it on my own (and that is the reason that I am looking for docker/singularity solution). What do you think about the above response from our tech support? If they are correct, is it possible that you fix this issue and build a new docker file to use with singularity on our cluster nodes?

Best Regards
Shahriar

**Comment by williww** [comment] 2022-08-03 07:19
hi @shahriar49,

it may be that singularity binds /home of the host automatically and thus "overlays" the /home of the container as described by your support, but IMHO this is not the default behavior of singularity (possibly an option in singularity.conf.. .).

as a solution you can try the following:
```
singularity exec --no-mount /home docker://davidfrantz/force:latest force
```

**Comment by shahriar49** [comment] 2022-08-03 16:46
Hi again @davidfrantz 

Thank you very much for your reply. I tried the above command. On singularity 3.6.4 it returned an error saying that --no-mount is not a valid argument. Then I loaded singularity 3.7.4 and got below error:

WARNING: Ignoring unknown mount type '/home'
FATAL:   "force": executable file not found in $PATH

I appreciate if you help me to pass this starting point asap!

**Comment by davidfrantz** [comment] 2022-08-04 07:27
Can you post the output of these commands?

```
singularity exec docker://davidfrantz/force:latest ls /home
singularity exec docker://davidfrantz/force:latest ls /home/docker/bin
singularity exec docker://davidfrantz/force:latest sh -c 'echo $PATH'
```

**Comment by shahriar49** [comment] 2022-08-04 16:03
Thanks for message. The result of running the first command is in the below file (including the warnings issues while pulling the docker file):
[log.txt](https://github.com/davidfrantz/force/files/9261262/log.txt)

The second command returned this:
```
[sheydari@colostate.edu@shas0137 force]$ singularity exec docker://davidfrantz/force:latest ls /home/docker/bin
INFO:    Using cached SIF image
/usr/bin/ls: cannot access '/home/docker/bin': No such file or directory
```

And the third command returned this:
```
[sheydari@colostate.edu@shas0137 force]$ singularity exec docker://davidfrantz/force:latest sh -c 'echo $PATH'
INFO:    Using cached SIF image
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/docker/bin
```

And just to check, when trying to execute force it returned below error:
```
[sheydari@colostate.edu@shas0137 force]$ singularity exec docker://davidfrantz/force:latest force
INFO:    Using cached SIF image
FATAL:   "force": executable file not found in $PATH
```

I am looking to hear back from you.

**Comment by williww** [comment] 2022-08-05 05:43
@davidfrantz's suggestion (ls /home, echo $PATH) clarifies the problem, but doesn't attempt the --no-mount solution.
This option, introduced with version 3.7, was precisely intended to avoid "overlaying" your /home.

IMHO you have a problem with that. I don't understand why my suggestion

```
singularity exec --no-mount /home docker://davidfrantz/force:latest force
```
fails. For me, with a freshly installed *singularity* and also the current *apptainer* version, it works without any problems

```
user@host:~/tmp$ singularity --version
singularity-ce version 3.10.2-jammy
# also apptainer version 1.1.0-rc.1 works OK!

user@host:~/tmp$ singularity exec --no-mount /home docker://davidfrantz/force:latest force
INFO: Converting OCI blobs to SIF format
INFO: Starting build...
Getting image source signatures
Copy blob f84fd646c710 done
Copy blob d0f3f0640507 done
Copy blob 790bce75ecd0 done
Copy blob 7b1a6ab2e44d done
Copy blob 730066957c22 done
Copy blob 36277c8e77a7 done
Copying config 37003e0c7b done
Writing manifest to image destination
Storing signatures
2022/08/05 06:53:42 info unpack layer: sha256:7b1a6ab2e44dbac178598dabe7cff59bd67233dba0b27e4fbd1f9d4b3c877a54
2022/08/05 06:53:43 info unpack layer: sha256:d0f3f0640507da9478f147187ca5942175497d486c39518f7af9a6a099337f85
2022/08/05 06:53:50 warn rootless{usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-ptp-helper} ignoring (usually) harmless EPERM on setxattr "security.capability"
2022/08/05 06:54:01 info unpack layer: sha256:730066957c220afc8bf88f0f0fa7d664e92ee18cfee75f94403bd5ab51e539d7
2022/08/05 06:54:02 info unpack layer: sha256:790bce75ecd05ef6a374ff4e693f518176774827b1d56c49974211180e5d064d
2022/08/05 06:54:02 info unpack layer: sha256:36277c8e77a7a07885fc3ea9a3f4c4986166513228fbb814da4020b05cf2f7f2
2022/08/05 06:54:02 info unpack layer: sha256:f84fd646c710b200ead3b5cc42d11195c07db564c13b23cad931522907ac0587
2022/08/05 06:54:02 warn rootless{home/docker/udf/.git/objects/pack/pack-dfb468919e1f7057c18b3ad9431a2eee1bf8d7bf.idx} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2022/08/05 06:54:02 warn rootless{home/docker/udf/.git/objects/pack/pack-dfb468919e1f7057c18b3ad9431a2eee1bf8d7bf.pack} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
INFO: Creating SIF file...

################################################# #########################

Hello dockers! You are currently running FORCE v. 3.7.7
```

What OS your *singularity* 3.7.4 is running on? How did you install? Package? From source?
Can there be a problem when calling *singularity* itself (wrong version is started, maybe because of $PATH...)? 

so, my suggestion:

```
uname -a
singularity --version
which singularity
```

**Comment by williww** [comment] 2022-08-05 07:17
Ok, @davidfrantz informed me about some mistake:

```
singularity exec --no-mount /home docker://davidfrantz/force:latest force
```

*/home* is wrong (**no** slash with *home*) , for this reason, @shahriar49, please use:

```
singularity exec --no-mount home docker://davidfrantz/force:latest force
```

Sorry for the inconvenience!

**Comment by shahriar49** [comment] 2022-08-05 12:28
Hi @williww 

Many thanks for your replies. I will try the suggestion soon but just a question: I am a user of a Linux cluster and just use software that the cluster admin have installed. They have singularity 3.7.4 available but not a more recent version. Will that cause a problem?

Best Regards
Shahriar

**Comment by davidfrantz** [comment] 2022-08-05 12:48
Dear @shahriar49,

please note that you are experiencing problems with singularity, or more precisely with the setup of singularity that was installed on your institute's system. The issue is not related to FORCE as such, therefore I will close this issue here now and classify it as off-topic. 

In my opinion, you have two possible courses of action. 

1) We provided you with some leads on working around the configuration provided by your admin.
2) Your admin provided you with a solution with which you can mitigate the issue yourself.

In case this does not work, I suggest you seek support from singularity developers.

Best regards,
David

**Closed by davidfrantz** 2022-08-05 12:48 UTC
